// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "stream.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic stream::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic stream::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> stream::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<32> stream::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool stream::ap_const_boolean_1 = true;
const bool stream::ap_const_boolean_0 = false;
const sc_lv<1> stream::ap_const_lv1_0 = "0";
const sc_lv<9> stream::ap_const_lv9_0 = "000000000";
const sc_lv<1> stream::ap_const_lv1_1 = "1";
const sc_lv<64> stream::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<67> stream::ap_const_lv67_0 = "0000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> stream::ap_const_lv32_3 = "11";
const sc_lv<32> stream::ap_const_lv32_42 = "1000010";
const sc_lv<32> stream::ap_const_lv32_1 = "1";
const sc_lv<32> stream::ap_const_lv32_2 = "10";
const sc_lv<9> stream::ap_const_lv9_1 = "1";
const sc_lv<2> stream::ap_const_lv2_3 = "11";
const sc_lv<9> stream::ap_const_lv9_1FF = "111111111";
const sc_lv<2> stream::ap_const_lv2_1 = "1";

stream::stream(sc_module_name name) : sc_module(name), mVcdFile(0) {
    brams_V_0_U = new stream_brams_V_0("brams_V_0_U");
    brams_V_0_U->clk(ap_clk);
    brams_V_0_U->reset(ap_rst);
    brams_V_0_U->address0(brams_V_0_address0);
    brams_V_0_U->ce0(brams_V_0_ce0);
    brams_V_0_U->we0(brams_V_0_we0);
    brams_V_0_U->d0(brams_V_0_d0);
    brams_V_0_U->address1(brams_V_0_address1);
    brams_V_0_U->ce1(brams_V_0_ce1);
    brams_V_0_U->q1(brams_V_0_q1);
    brams_V_1_U = new stream_brams_V_0("brams_V_1_U");
    brams_V_1_U->clk(ap_clk);
    brams_V_1_U->reset(ap_rst);
    brams_V_1_U->address0(brams_V_1_address0);
    brams_V_1_U->ce0(brams_V_1_ce0);
    brams_V_1_U->we0(brams_V_1_we0);
    brams_V_1_U->d0(brams_V_1_d0);
    brams_V_1_U->address1(brams_V_1_address1);
    brams_V_1_U->ce1(brams_V_1_ce1);
    brams_V_1_U->q1(brams_V_1_q1);
    brams_V_2_U = new stream_brams_V_0("brams_V_2_U");
    brams_V_2_U->clk(ap_clk);
    brams_V_2_U->reset(ap_rst);
    brams_V_2_U->address0(brams_V_2_address0);
    brams_V_2_U->ce0(brams_V_2_ce0);
    brams_V_2_U->we0(brams_V_2_we0);
    brams_V_2_U->d0(brams_V_2_d0);
    brams_V_2_U->address1(brams_V_2_address1);
    brams_V_2_U->ce1(brams_V_2_ce1);
    brams_V_2_U->q1(brams_V_2_q1);
    brams_V_3_U = new stream_brams_V_0("brams_V_3_U");
    brams_V_3_U->clk(ap_clk);
    brams_V_3_U->reset(ap_rst);
    brams_V_3_U->address0(brams_V_3_address0);
    brams_V_3_U->ce0(brams_V_3_ce0);
    brams_V_3_U->we0(brams_V_3_we0);
    brams_V_3_U->d0(brams_V_3_d0);
    brams_V_3_U->address1(brams_V_3_address1);
    brams_V_3_U->ce1(brams_V_3_ce1);
    brams_V_3_U->q1(brams_V_3_q1);
    stream_mux_42_67_bkb_U1 = new stream_mux_42_67_bkb<1,1,67,67,67,67,2,67>("stream_mux_42_67_bkb_U1");
    stream_mux_42_67_bkb_U1->din0(brams_V_0_q1);
    stream_mux_42_67_bkb_U1->din1(brams_V_1_q1);
    stream_mux_42_67_bkb_U1->din2(brams_V_2_q1);
    stream_mux_42_67_bkb_U1->din3(brams_V_3_q1);
    stream_mux_42_67_bkb_U1->din4(readidx_V_load_reg_859);
    stream_mux_42_67_bkb_U1->dout(p_Val2_s_fu_708_p6);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln214_fu_755_p2);
    sensitive << ( readidx_V_load_reg_859 );

    SC_METHOD(thread_add_ln700_1_fu_655_p2);
    sensitive << ( ap_sig_allocacmp_t_V_1 );

    SC_METHOD(thread_add_ln700_2_fu_690_p2);
    sensitive << ( rdptr_V );

    SC_METHOD(thread_add_ln700_fu_623_p2);
    sensitive << ( wrptr_V );

    SC_METHOD(thread_add_ln701_fu_702_p2);
    sensitive << ( ap_phi_mux_t_V_3_phi_fu_261_p4 );

    SC_METHOD(thread_and_ln791_1_fu_522_p2);
    sensitive << ( icmp_ln791_reg_836 );
    sensitive << ( or_ln791_2_fu_517_p2 );

    SC_METHOD(thread_and_ln791_2_fu_548_p2);
    sensitive << ( lastvalid_read_reg_772 );
    sensitive << ( icmp_ln879_2_reg_808 );

    SC_METHOD(thread_and_ln791_3_fu_552_p2);
    sensitive << ( icmp_ln879_reg_795 );
    sensitive << ( xor_ln791_fu_543_p2 );

    SC_METHOD(thread_and_ln791_4_fu_557_p2);
    sensitive << ( and_ln791_3_fu_552_p2 );
    sensitive << ( and_ln791_2_fu_548_p2 );

    SC_METHOD(thread_and_ln791_5_fu_569_p2);
    sensitive << ( and_ln791_1_fu_522_p2 );
    sensitive << ( xor_ln791_1_fu_563_p2 );

    SC_METHOD(thread_and_ln791_fu_498_p2);
    sensitive << ( icmp_ln879_4_reg_819 );
    sensitive << ( icmp_ln879_3_reg_830 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_idle_pp0_0to2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_phi_mux_p_0202_phi_fu_328_p4);
    sensitive << ( icmp_ln895_reg_855 );
    sensitive << ( ap_phi_reg_pp0_iter3_p_0202_reg_325 );
    sensitive << ( p_Result_2_fu_721_p1 );

    SC_METHOD(thread_ap_phi_mux_ptrsep_V_flag_1_phi_fu_285_p4);
    sensitive << ( icmp_ln895_reg_855 );
    sensitive << ( icmp_ln879_1_reg_885 );
    sensitive << ( ap_phi_reg_pp0_iter3_ptrsep_V_flag_0_reg_268 );
    sensitive << ( ap_phi_reg_pp0_iter3_ptrsep_V_flag_1_reg_281 );

    SC_METHOD(thread_ap_phi_mux_ptrsep_V_flag_2_phi_fu_306_p4);
    sensitive << ( icmp_ln895_reg_855 );
    sensitive << ( ap_phi_reg_pp0_iter3_ptrsep_V_flag_0_reg_268 );
    sensitive << ( ap_phi_mux_ptrsep_V_flag_1_phi_fu_285_p4 );
    sensitive << ( ap_phi_reg_pp0_iter3_ptrsep_V_flag_2_reg_303 );

    SC_METHOD(thread_ap_phi_mux_ptrsep_V_new_1_phi_fu_296_p4);
    sensitive << ( t_V_3_reg_258 );
    sensitive << ( icmp_ln895_reg_855 );
    sensitive << ( icmp_ln879_1_reg_885 );
    sensitive << ( ap_phi_reg_pp0_iter3_ptrsep_V_new_1_reg_293 );

    SC_METHOD(thread_ap_phi_mux_ptrsep_V_new_2_phi_fu_317_p4);
    sensitive << ( icmp_ln895_reg_855 );
    sensitive << ( ap_phi_mux_ptrsep_V_new_1_phi_fu_296_p4 );
    sensitive << ( ap_phi_reg_pp0_iter3_ptrsep_V_new_2_reg_314 );

    SC_METHOD(thread_ap_phi_mux_t_V_3_phi_fu_261_p4);
    sensitive << ( or_ln27_reg_847 );
    sensitive << ( add_ln700_1_fu_655_p2 );
    sensitive << ( ap_phi_reg_pp0_iter2_t_V_3_reg_258 );
    sensitive << ( ap_sig_allocacmp_t_V_1 );

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_ptrsep_V_flag_0_reg_268);

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_ptrsep_V_flag_1_reg_281);

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_ptrsep_V_new_1_reg_293);

    SC_METHOD(thread_ap_phi_reg_pp0_iter2_t_V_3_reg_258);

    SC_METHOD(thread_ap_phi_reg_pp0_iter3_p_0202_reg_325);

    SC_METHOD(thread_ap_phi_reg_pp0_iter3_ptrsep_V_flag_2_reg_303);

    SC_METHOD(thread_ap_phi_reg_pp0_iter3_ptrsep_V_new_2_reg_314);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_phi_mux_p_0202_phi_fu_328_p4 );

    SC_METHOD(thread_ap_sig_allocacmp_readidx_V_load);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( readidx_V );
    sensitive << ( icmp_ln895_reg_855 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( add_ln214_fu_755_p2 );

    SC_METHOD(thread_ap_sig_allocacmp_t_V_1);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ptrsep_V );
    sensitive << ( ap_phi_mux_ptrsep_V_flag_2_phi_fu_306_p4 );
    sensitive << ( ap_phi_mux_ptrsep_V_new_2_phi_fu_317_p4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_brams_V_0_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( zext_ln544_fu_615_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_brams_V_0_address1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln544_1_fu_672_p1 );

    SC_METHOD(thread_brams_V_0_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_brams_V_0_ce1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_brams_V_0_d0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( lastvalid_read_reg_772 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sel_tmp1_fu_593_p5 );
    sensitive << ( p_Result_3_3_fu_476_p5 );

    SC_METHOD(thread_brams_V_0_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_ln27_fu_381_p2 );

    SC_METHOD(thread_brams_V_1_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( zext_ln544_fu_615_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_brams_V_1_address1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln544_1_fu_672_p1 );

    SC_METHOD(thread_brams_V_1_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_brams_V_1_ce1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_brams_V_1_d0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( lastvalid_read_reg_772 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_fu_413_p4 );
    sensitive << ( tmp_6_fu_575_p4 );

    SC_METHOD(thread_brams_V_1_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_ln27_fu_381_p2 );

    SC_METHOD(thread_brams_V_2_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( zext_ln544_fu_615_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_brams_V_2_address1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln544_1_fu_672_p1 );

    SC_METHOD(thread_brams_V_2_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_brams_V_2_ce1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_brams_V_2_d0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( lastvalid_read_reg_772 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_fu_434_p4 );
    sensitive << ( tmp_5_fu_502_p4 );

    SC_METHOD(thread_brams_V_2_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_ln27_fu_381_p2 );

    SC_METHOD(thread_brams_V_3_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( zext_ln544_fu_615_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_brams_V_3_address1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln544_1_fu_672_p1 );

    SC_METHOD(thread_brams_V_3_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_brams_V_3_ce1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_brams_V_3_d0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( lastvalid_read_reg_772 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_3_fu_459_p4 );
    sensitive << ( tmp_4_fu_488_p4 );

    SC_METHOD(thread_brams_V_3_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_ln27_fu_381_p2 );

    SC_METHOD(thread_candout_V);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln895_reg_855 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( p_Val2_s_fu_708_p6 );

    SC_METHOD(thread_candout_V_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln895_reg_855 );

    SC_METHOD(thread_first);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln895_reg_855 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( p_Val2_s_fu_708_p6 );

    SC_METHOD(thread_first_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln895_reg_855 );

    SC_METHOD(thread_icmp_ln791_1_fu_371_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_ln791_fu_359_p2 );

    SC_METHOD(thread_icmp_ln791_fu_365_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_ln791_fu_359_p2 );

    SC_METHOD(thread_icmp_ln879_1_fu_684_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln895_fu_662_p2 );
    sensitive << ( ap_sig_allocacmp_readidx_V_load );

    SC_METHOD(thread_icmp_ln879_2_fu_341_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( candin_1_V );

    SC_METHOD(thread_icmp_ln879_3_fu_353_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( candin_3_V );

    SC_METHOD(thread_icmp_ln879_4_fu_347_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( candin_2_V );

    SC_METHOD(thread_icmp_ln879_fu_335_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( candin_0_V );

    SC_METHOD(thread_icmp_ln895_fu_662_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_phi_mux_t_V_3_phi_fu_261_p4 );

    SC_METHOD(thread_last);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln895_reg_855 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( p_Val2_s_fu_708_p6 );

    SC_METHOD(thread_last_ap_vld);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln895_reg_855 );

    SC_METHOD(thread_or_ln27_fu_381_p2);
    sensitive << ( write_r );
    sensitive << ( eventstart_read_reg_783 );

    SC_METHOD(thread_or_ln69_fu_635_p2);
    sensitive << ( lastvalid_read_reg_772 );
    sensitive << ( eventstart_read_reg_783 );

    SC_METHOD(thread_or_ln791_1_fu_512_p2);
    sensitive << ( icmp_ln879_reg_795 );
    sensitive << ( xor_ln879_fu_408_p2 );

    SC_METHOD(thread_or_ln791_2_fu_517_p2);
    sensitive << ( icmp_ln791_1_reg_841 );
    sensitive << ( or_ln791_1_fu_512_p2 );

    SC_METHOD(thread_or_ln791_fu_359_p2);
    sensitive << ( candin_2_V );
    sensitive << ( candin_3_V );

    SC_METHOD(thread_p_Result_18_1_fu_397_p5);
    sensitive << ( candin_1_V_read_reg_803 );

    SC_METHOD(thread_p_Result_18_2_fu_423_p5);
    sensitive << ( candin_2_V_read_reg_814 );

    SC_METHOD(thread_p_Result_18_3_fu_443_p5);
    sensitive << ( candin_3_V_read_reg_825 );

    SC_METHOD(thread_p_Result_2_fu_721_p1);
    sensitive << ( p_Val2_s_fu_708_p6 );

    SC_METHOD(thread_p_Result_3_3_fu_476_p5);
    sensitive << ( p_Result_s_fu_386_p5 );
    sensitive << ( tmp_1_fu_469_p3 );

    SC_METHOD(thread_p_Result_s_fu_386_p5);
    sensitive << ( candin_0_V_read_reg_789 );

    SC_METHOD(thread_sel_tmp1_fu_593_p5);
    sensitive << ( candin_0_V_read_reg_789 );
    sensitive << ( icmp_ln879_reg_795 );
    sensitive << ( and_ln791_4_fu_557_p2 );

    SC_METHOD(thread_tmp_1_fu_469_p3);
    sensitive << ( icmp_ln879_reg_795 );

    SC_METHOD(thread_tmp_2_fu_434_p4);
    sensitive << ( icmp_ln879_4_reg_819 );
    sensitive << ( p_Result_18_2_fu_423_p5 );

    SC_METHOD(thread_tmp_3_fu_459_p4);
    sensitive << ( p_Result_18_3_fu_443_p5 );
    sensitive << ( xor_ln879_1_fu_454_p2 );

    SC_METHOD(thread_tmp_4_fu_488_p4);
    sensitive << ( xor_ln879_1_fu_454_p2 );
    sensitive << ( tmp_3_fu_459_p4 );

    SC_METHOD(thread_tmp_5_fu_502_p4);
    sensitive << ( tmp_2_fu_434_p4 );
    sensitive << ( and_ln791_fu_498_p2 );

    SC_METHOD(thread_tmp_6_fu_575_p4);
    sensitive << ( tmp_fu_413_p4 );
    sensitive << ( and_ln791_5_fu_569_p2 );

    SC_METHOD(thread_tmp_fu_413_p4);
    sensitive << ( p_Result_18_1_fu_397_p5 );
    sensitive << ( xor_ln879_fu_408_p2 );

    SC_METHOD(thread_xor_ln69_fu_639_p2);
    sensitive << ( lastvalid_read_reg_772 );

    SC_METHOD(thread_xor_ln791_1_fu_563_p2);
    sensitive << ( and_ln791_4_fu_557_p2 );

    SC_METHOD(thread_xor_ln791_fu_543_p2);
    sensitive << ( icmp_ln791_1_reg_841 );

    SC_METHOD(thread_xor_ln879_1_fu_454_p2);
    sensitive << ( icmp_ln879_3_reg_830 );

    SC_METHOD(thread_xor_ln879_fu_408_p2);
    sensitive << ( icmp_ln879_2_reg_808 );

    SC_METHOD(thread_zext_ln544_1_fu_672_p1);
    sensitive << ( rdptr_V );

    SC_METHOD(thread_zext_ln544_fu_615_p1);
    sensitive << ( wrptr_V );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    write_r = "0";
    ptrsep_V = "000000000";
    wrptr_V = "000000000";
    rdptr_V = "000000000";
    readidx_V = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "stream_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, candin_0_V, "(port)candin_0_V");
    sc_trace(mVcdFile, candin_1_V, "(port)candin_1_V");
    sc_trace(mVcdFile, candin_2_V, "(port)candin_2_V");
    sc_trace(mVcdFile, candin_3_V, "(port)candin_3_V");
    sc_trace(mVcdFile, candout_V, "(port)candout_V");
    sc_trace(mVcdFile, candout_V_ap_vld, "(port)candout_V_ap_vld");
    sc_trace(mVcdFile, eventstart, "(port)eventstart");
    sc_trace(mVcdFile, lastvalid, "(port)lastvalid");
    sc_trace(mVcdFile, first, "(port)first");
    sc_trace(mVcdFile, first_ap_vld, "(port)first_ap_vld");
    sc_trace(mVcdFile, last, "(port)last");
    sc_trace(mVcdFile, last_ap_vld, "(port)last_ap_vld");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, write_r, "write_r");
    sc_trace(mVcdFile, ptrsep_V, "ptrsep_V");
    sc_trace(mVcdFile, wrptr_V, "wrptr_V");
    sc_trace(mVcdFile, brams_V_0_address0, "brams_V_0_address0");
    sc_trace(mVcdFile, brams_V_0_ce0, "brams_V_0_ce0");
    sc_trace(mVcdFile, brams_V_0_we0, "brams_V_0_we0");
    sc_trace(mVcdFile, brams_V_0_d0, "brams_V_0_d0");
    sc_trace(mVcdFile, brams_V_0_address1, "brams_V_0_address1");
    sc_trace(mVcdFile, brams_V_0_ce1, "brams_V_0_ce1");
    sc_trace(mVcdFile, brams_V_0_q1, "brams_V_0_q1");
    sc_trace(mVcdFile, brams_V_1_address0, "brams_V_1_address0");
    sc_trace(mVcdFile, brams_V_1_ce0, "brams_V_1_ce0");
    sc_trace(mVcdFile, brams_V_1_we0, "brams_V_1_we0");
    sc_trace(mVcdFile, brams_V_1_d0, "brams_V_1_d0");
    sc_trace(mVcdFile, brams_V_1_address1, "brams_V_1_address1");
    sc_trace(mVcdFile, brams_V_1_ce1, "brams_V_1_ce1");
    sc_trace(mVcdFile, brams_V_1_q1, "brams_V_1_q1");
    sc_trace(mVcdFile, brams_V_2_address0, "brams_V_2_address0");
    sc_trace(mVcdFile, brams_V_2_ce0, "brams_V_2_ce0");
    sc_trace(mVcdFile, brams_V_2_we0, "brams_V_2_we0");
    sc_trace(mVcdFile, brams_V_2_d0, "brams_V_2_d0");
    sc_trace(mVcdFile, brams_V_2_address1, "brams_V_2_address1");
    sc_trace(mVcdFile, brams_V_2_ce1, "brams_V_2_ce1");
    sc_trace(mVcdFile, brams_V_2_q1, "brams_V_2_q1");
    sc_trace(mVcdFile, brams_V_3_address0, "brams_V_3_address0");
    sc_trace(mVcdFile, brams_V_3_ce0, "brams_V_3_ce0");
    sc_trace(mVcdFile, brams_V_3_we0, "brams_V_3_we0");
    sc_trace(mVcdFile, brams_V_3_d0, "brams_V_3_d0");
    sc_trace(mVcdFile, brams_V_3_address1, "brams_V_3_address1");
    sc_trace(mVcdFile, brams_V_3_ce1, "brams_V_3_ce1");
    sc_trace(mVcdFile, brams_V_3_q1, "brams_V_3_q1");
    sc_trace(mVcdFile, rdptr_V, "rdptr_V");
    sc_trace(mVcdFile, readidx_V, "readidx_V");
    sc_trace(mVcdFile, t_V_3_reg_258, "t_V_3_reg_258");
    sc_trace(mVcdFile, lastvalid_read_reg_772, "lastvalid_read_reg_772");
    sc_trace(mVcdFile, eventstart_read_reg_783, "eventstart_read_reg_783");
    sc_trace(mVcdFile, candin_0_V_read_reg_789, "candin_0_V_read_reg_789");
    sc_trace(mVcdFile, icmp_ln879_fu_335_p2, "icmp_ln879_fu_335_p2");
    sc_trace(mVcdFile, icmp_ln879_reg_795, "icmp_ln879_reg_795");
    sc_trace(mVcdFile, candin_1_V_read_reg_803, "candin_1_V_read_reg_803");
    sc_trace(mVcdFile, icmp_ln879_2_fu_341_p2, "icmp_ln879_2_fu_341_p2");
    sc_trace(mVcdFile, icmp_ln879_2_reg_808, "icmp_ln879_2_reg_808");
    sc_trace(mVcdFile, candin_2_V_read_reg_814, "candin_2_V_read_reg_814");
    sc_trace(mVcdFile, icmp_ln879_4_fu_347_p2, "icmp_ln879_4_fu_347_p2");
    sc_trace(mVcdFile, icmp_ln879_4_reg_819, "icmp_ln879_4_reg_819");
    sc_trace(mVcdFile, candin_3_V_read_reg_825, "candin_3_V_read_reg_825");
    sc_trace(mVcdFile, icmp_ln879_3_fu_353_p2, "icmp_ln879_3_fu_353_p2");
    sc_trace(mVcdFile, icmp_ln879_3_reg_830, "icmp_ln879_3_reg_830");
    sc_trace(mVcdFile, icmp_ln791_fu_365_p2, "icmp_ln791_fu_365_p2");
    sc_trace(mVcdFile, icmp_ln791_reg_836, "icmp_ln791_reg_836");
    sc_trace(mVcdFile, icmp_ln791_1_fu_371_p2, "icmp_ln791_1_fu_371_p2");
    sc_trace(mVcdFile, icmp_ln791_1_reg_841, "icmp_ln791_1_reg_841");
    sc_trace(mVcdFile, or_ln27_fu_381_p2, "or_ln27_fu_381_p2");
    sc_trace(mVcdFile, or_ln27_reg_847, "or_ln27_reg_847");
    sc_trace(mVcdFile, or_ln69_fu_635_p2, "or_ln69_fu_635_p2");
    sc_trace(mVcdFile, icmp_ln895_fu_662_p2, "icmp_ln895_fu_662_p2");
    sc_trace(mVcdFile, icmp_ln895_reg_855, "icmp_ln895_reg_855");
    sc_trace(mVcdFile, readidx_V_load_reg_859, "readidx_V_load_reg_859");
    sc_trace(mVcdFile, icmp_ln879_1_fu_684_p2, "icmp_ln879_1_fu_684_p2");
    sc_trace(mVcdFile, icmp_ln879_1_reg_885, "icmp_ln879_1_reg_885");
    sc_trace(mVcdFile, add_ln701_fu_702_p2, "add_ln701_fu_702_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_phi_mux_t_V_3_phi_fu_261_p4, "ap_phi_mux_t_V_3_phi_fu_261_p4");
    sc_trace(mVcdFile, add_ln700_1_fu_655_p2, "add_ln700_1_fu_655_p2");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter2_t_V_3_reg_258, "ap_phi_reg_pp0_iter2_t_V_3_reg_258");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_ptrsep_V_flag_0_reg_268, "ap_phi_reg_pp0_iter0_ptrsep_V_flag_0_reg_268");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter1_ptrsep_V_flag_0_reg_268, "ap_phi_reg_pp0_iter1_ptrsep_V_flag_0_reg_268");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter2_ptrsep_V_flag_0_reg_268, "ap_phi_reg_pp0_iter2_ptrsep_V_flag_0_reg_268");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter3_ptrsep_V_flag_0_reg_268, "ap_phi_reg_pp0_iter3_ptrsep_V_flag_0_reg_268");
    sc_trace(mVcdFile, ap_phi_mux_ptrsep_V_flag_1_phi_fu_285_p4, "ap_phi_mux_ptrsep_V_flag_1_phi_fu_285_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_ptrsep_V_flag_1_reg_281, "ap_phi_reg_pp0_iter0_ptrsep_V_flag_1_reg_281");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter1_ptrsep_V_flag_1_reg_281, "ap_phi_reg_pp0_iter1_ptrsep_V_flag_1_reg_281");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter2_ptrsep_V_flag_1_reg_281, "ap_phi_reg_pp0_iter2_ptrsep_V_flag_1_reg_281");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter3_ptrsep_V_flag_1_reg_281, "ap_phi_reg_pp0_iter3_ptrsep_V_flag_1_reg_281");
    sc_trace(mVcdFile, ap_phi_mux_ptrsep_V_new_1_phi_fu_296_p4, "ap_phi_mux_ptrsep_V_new_1_phi_fu_296_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_ptrsep_V_new_1_reg_293, "ap_phi_reg_pp0_iter0_ptrsep_V_new_1_reg_293");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter1_ptrsep_V_new_1_reg_293, "ap_phi_reg_pp0_iter1_ptrsep_V_new_1_reg_293");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter2_ptrsep_V_new_1_reg_293, "ap_phi_reg_pp0_iter2_ptrsep_V_new_1_reg_293");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter3_ptrsep_V_new_1_reg_293, "ap_phi_reg_pp0_iter3_ptrsep_V_new_1_reg_293");
    sc_trace(mVcdFile, ap_phi_mux_ptrsep_V_flag_2_phi_fu_306_p4, "ap_phi_mux_ptrsep_V_flag_2_phi_fu_306_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter3_ptrsep_V_flag_2_reg_303, "ap_phi_reg_pp0_iter3_ptrsep_V_flag_2_reg_303");
    sc_trace(mVcdFile, ap_phi_mux_ptrsep_V_new_2_phi_fu_317_p4, "ap_phi_mux_ptrsep_V_new_2_phi_fu_317_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter3_ptrsep_V_new_2_reg_314, "ap_phi_reg_pp0_iter3_ptrsep_V_new_2_reg_314");
    sc_trace(mVcdFile, ap_phi_mux_p_0202_phi_fu_328_p4, "ap_phi_mux_p_0202_phi_fu_328_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter3_p_0202_reg_325, "ap_phi_reg_pp0_iter3_p_0202_reg_325");
    sc_trace(mVcdFile, p_Result_2_fu_721_p1, "p_Result_2_fu_721_p1");
    sc_trace(mVcdFile, zext_ln544_fu_615_p1, "zext_ln544_fu_615_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, zext_ln544_1_fu_672_p1, "zext_ln544_1_fu_672_p1");
    sc_trace(mVcdFile, xor_ln69_fu_639_p2, "xor_ln69_fu_639_p2");
    sc_trace(mVcdFile, ap_sig_allocacmp_t_V_1, "ap_sig_allocacmp_t_V_1");
    sc_trace(mVcdFile, add_ln700_fu_623_p2, "add_ln700_fu_623_p2");
    sc_trace(mVcdFile, add_ln700_2_fu_690_p2, "add_ln700_2_fu_690_p2");
    sc_trace(mVcdFile, add_ln214_fu_755_p2, "add_ln214_fu_755_p2");
    sc_trace(mVcdFile, ap_sig_allocacmp_readidx_V_load, "ap_sig_allocacmp_readidx_V_load");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, or_ln791_fu_359_p2, "or_ln791_fu_359_p2");
    sc_trace(mVcdFile, p_Result_18_1_fu_397_p5, "p_Result_18_1_fu_397_p5");
    sc_trace(mVcdFile, xor_ln879_fu_408_p2, "xor_ln879_fu_408_p2");
    sc_trace(mVcdFile, p_Result_18_2_fu_423_p5, "p_Result_18_2_fu_423_p5");
    sc_trace(mVcdFile, p_Result_18_3_fu_443_p5, "p_Result_18_3_fu_443_p5");
    sc_trace(mVcdFile, xor_ln879_1_fu_454_p2, "xor_ln879_1_fu_454_p2");
    sc_trace(mVcdFile, p_Result_s_fu_386_p5, "p_Result_s_fu_386_p5");
    sc_trace(mVcdFile, tmp_1_fu_469_p3, "tmp_1_fu_469_p3");
    sc_trace(mVcdFile, tmp_3_fu_459_p4, "tmp_3_fu_459_p4");
    sc_trace(mVcdFile, tmp_2_fu_434_p4, "tmp_2_fu_434_p4");
    sc_trace(mVcdFile, and_ln791_fu_498_p2, "and_ln791_fu_498_p2");
    sc_trace(mVcdFile, or_ln791_1_fu_512_p2, "or_ln791_1_fu_512_p2");
    sc_trace(mVcdFile, or_ln791_2_fu_517_p2, "or_ln791_2_fu_517_p2");
    sc_trace(mVcdFile, tmp_4_fu_488_p4, "tmp_4_fu_488_p4");
    sc_trace(mVcdFile, tmp_5_fu_502_p4, "tmp_5_fu_502_p4");
    sc_trace(mVcdFile, xor_ln791_fu_543_p2, "xor_ln791_fu_543_p2");
    sc_trace(mVcdFile, and_ln791_3_fu_552_p2, "and_ln791_3_fu_552_p2");
    sc_trace(mVcdFile, and_ln791_2_fu_548_p2, "and_ln791_2_fu_548_p2");
    sc_trace(mVcdFile, and_ln791_4_fu_557_p2, "and_ln791_4_fu_557_p2");
    sc_trace(mVcdFile, and_ln791_1_fu_522_p2, "and_ln791_1_fu_522_p2");
    sc_trace(mVcdFile, xor_ln791_1_fu_563_p2, "xor_ln791_1_fu_563_p2");
    sc_trace(mVcdFile, tmp_fu_413_p4, "tmp_fu_413_p4");
    sc_trace(mVcdFile, and_ln791_5_fu_569_p2, "and_ln791_5_fu_569_p2");
    sc_trace(mVcdFile, tmp_6_fu_575_p4, "tmp_6_fu_575_p4");
    sc_trace(mVcdFile, sel_tmp1_fu_593_p5, "sel_tmp1_fu_593_p5");
    sc_trace(mVcdFile, p_Result_3_3_fu_476_p5, "p_Result_3_3_fu_476_p5");
    sc_trace(mVcdFile, p_Val2_s_fu_708_p6, "p_Val2_s_fu_708_p6");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to2, "ap_idle_pp0_0to2");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
    mHdltvinHandle.open("stream.hdltvin.dat");
    mHdltvoutHandle.open("stream.hdltvout.dat");
}

stream::~stream() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete brams_V_0_U;
    delete brams_V_1_U;
    delete brams_V_2_U;
    delete brams_V_3_U;
    delete stream_mux_42_67_bkb_U1;
}

void stream::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, or_ln27_reg_847.read())) {
            ap_phi_reg_pp0_iter3_ptrsep_V_flag_0_reg_268 = ap_const_lv1_0;
        } else if (esl_seteq<1,1,1>(or_ln27_reg_847.read(), ap_const_lv1_1)) {
            ap_phi_reg_pp0_iter3_ptrsep_V_flag_0_reg_268 = ap_const_lv1_1;
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter3_ptrsep_V_flag_0_reg_268 = ap_phi_reg_pp0_iter2_ptrsep_V_flag_0_reg_268.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_fu_662_p2.read()) && 
             esl_seteq<1,1,1>(icmp_ln879_1_fu_684_p2.read(), ap_const_lv1_1))) {
            ap_phi_reg_pp0_iter3_ptrsep_V_flag_1_reg_281 = ap_const_lv1_1;
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter3_ptrsep_V_flag_1_reg_281 = ap_phi_reg_pp0_iter2_ptrsep_V_flag_1_reg_281.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_fu_662_p2.read()) && 
             esl_seteq<1,1,1>(icmp_ln879_1_fu_684_p2.read(), ap_const_lv1_1))) {
            ap_phi_reg_pp0_iter3_ptrsep_V_new_1_reg_293 = add_ln701_fu_702_p2.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter3_ptrsep_V_new_1_reg_293 = ap_phi_reg_pp0_iter2_ptrsep_V_new_1_reg_293.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, or_ln27_reg_847.read())) {
            t_V_3_reg_258 = ap_sig_allocacmp_t_V_1.read();
        } else if (esl_seteq<1,1,1>(or_ln27_reg_847.read(), ap_const_lv1_1)) {
            t_V_3_reg_258 = add_ln700_1_fu_655_p2.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            t_V_3_reg_258 = ap_phi_reg_pp0_iter2_t_V_3_reg_258.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_phi_reg_pp0_iter1_ptrsep_V_flag_0_reg_268 = ap_phi_reg_pp0_iter0_ptrsep_V_flag_0_reg_268.read();
        ap_phi_reg_pp0_iter1_ptrsep_V_flag_1_reg_281 = ap_phi_reg_pp0_iter0_ptrsep_V_flag_1_reg_281.read();
        ap_phi_reg_pp0_iter1_ptrsep_V_new_1_reg_293 = ap_phi_reg_pp0_iter0_ptrsep_V_new_1_reg_293.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        ap_phi_reg_pp0_iter2_ptrsep_V_flag_0_reg_268 = ap_phi_reg_pp0_iter1_ptrsep_V_flag_0_reg_268.read();
        ap_phi_reg_pp0_iter2_ptrsep_V_flag_1_reg_281 = ap_phi_reg_pp0_iter1_ptrsep_V_flag_1_reg_281.read();
        ap_phi_reg_pp0_iter2_ptrsep_V_new_1_reg_293 = ap_phi_reg_pp0_iter1_ptrsep_V_new_1_reg_293.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        candin_0_V_read_reg_789 = candin_0_V.read();
        candin_1_V_read_reg_803 = candin_1_V.read();
        candin_2_V_read_reg_814 = candin_2_V.read();
        candin_3_V_read_reg_825 = candin_3_V.read();
        eventstart_read_reg_783 =  (sc_lv<1>) (eventstart.read());
        icmp_ln791_1_reg_841 = icmp_ln791_1_fu_371_p2.read();
        icmp_ln791_reg_836 = icmp_ln791_fu_365_p2.read();
        icmp_ln879_2_reg_808 = icmp_ln879_2_fu_341_p2.read();
        icmp_ln879_3_reg_830 = icmp_ln879_3_fu_353_p2.read();
        icmp_ln879_4_reg_819 = icmp_ln879_4_fu_347_p2.read();
        icmp_ln879_reg_795 = icmp_ln879_fu_335_p2.read();
        lastvalid_read_reg_772 =  (sc_lv<1>) (lastvalid.read());
        or_ln27_reg_847 = or_ln27_fu_381_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_fu_662_p2.read()))) {
        icmp_ln879_1_reg_885 = icmp_ln879_1_fu_684_p2.read();
        readidx_V_load_reg_859 = ap_sig_allocacmp_readidx_V_load.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln895_reg_855 = icmp_ln895_fu_662_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_ptrsep_V_flag_2_phi_fu_306_p4.read()))) {
        ptrsep_V = ap_phi_mux_ptrsep_V_new_2_phi_fu_317_p4.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_fu_662_p2.read()) && esl_seteq<1,1,1>(icmp_ln879_1_fu_684_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        rdptr_V = add_ln700_2_fu_690_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read()))) {
        readidx_V = add_ln214_fu_755_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(or_ln69_fu_635_p2.read(), ap_const_lv1_1))) {
        write_r = xor_ln69_fu_639_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(or_ln27_fu_381_p2.read(), ap_const_lv1_1))) {
        wrptr_V = add_ln700_fu_623_p2.read();
    }
}

void stream::thread_add_ln214_fu_755_p2() {
    add_ln214_fu_755_p2 = (!readidx_V_load_reg_859.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(readidx_V_load_reg_859.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void stream::thread_add_ln700_1_fu_655_p2() {
    add_ln700_1_fu_655_p2 = (!ap_sig_allocacmp_t_V_1.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(ap_sig_allocacmp_t_V_1.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void stream::thread_add_ln700_2_fu_690_p2() {
    add_ln700_2_fu_690_p2 = (!rdptr_V.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(rdptr_V.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void stream::thread_add_ln700_fu_623_p2() {
    add_ln700_fu_623_p2 = (!wrptr_V.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(wrptr_V.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void stream::thread_add_ln701_fu_702_p2() {
    add_ln701_fu_702_p2 = (!ap_phi_mux_t_V_3_phi_fu_261_p4.read().is_01() || !ap_const_lv9_1FF.is_01())? sc_lv<9>(): (sc_biguint<9>(ap_phi_mux_t_V_3_phi_fu_261_p4.read()) + sc_bigint<9>(ap_const_lv9_1FF));
}

void stream::thread_and_ln791_1_fu_522_p2() {
    and_ln791_1_fu_522_p2 = (or_ln791_2_fu_517_p2.read() & icmp_ln791_reg_836.read());
}

void stream::thread_and_ln791_2_fu_548_p2() {
    and_ln791_2_fu_548_p2 = (icmp_ln879_2_reg_808.read() & lastvalid_read_reg_772.read());
}

void stream::thread_and_ln791_3_fu_552_p2() {
    and_ln791_3_fu_552_p2 = (icmp_ln879_reg_795.read() & xor_ln791_fu_543_p2.read());
}

void stream::thread_and_ln791_4_fu_557_p2() {
    and_ln791_4_fu_557_p2 = (and_ln791_3_fu_552_p2.read() & and_ln791_2_fu_548_p2.read());
}

void stream::thread_and_ln791_5_fu_569_p2() {
    and_ln791_5_fu_569_p2 = (and_ln791_1_fu_522_p2.read() & xor_ln791_1_fu_563_p2.read());
}

void stream::thread_and_ln791_fu_498_p2() {
    and_ln791_fu_498_p2 = (icmp_ln879_3_reg_830.read() & icmp_ln879_4_reg_819.read());
}

void stream::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void stream::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void stream::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void stream::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void stream::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void stream::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read());
}

void stream::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void stream::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void stream::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void stream::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void stream::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void stream::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void stream::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void stream::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void stream::thread_ap_idle_pp0_0to2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0_0to2 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to2 = ap_const_logic_0;
    }
}

void stream::thread_ap_phi_mux_p_0202_phi_fu_328_p4() {
    if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read())) {
        ap_phi_mux_p_0202_phi_fu_328_p4 = p_Result_2_fu_721_p1.read();
    } else if (esl_seteq<1,1,1>(icmp_ln895_reg_855.read(), ap_const_lv1_1)) {
        ap_phi_mux_p_0202_phi_fu_328_p4 = ap_const_lv1_0;
    } else {
        ap_phi_mux_p_0202_phi_fu_328_p4 = ap_phi_reg_pp0_iter3_p_0202_reg_325.read();
    }
}

void stream::thread_ap_phi_mux_ptrsep_V_flag_1_phi_fu_285_p4() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln879_1_reg_885.read()))) {
        ap_phi_mux_ptrsep_V_flag_1_phi_fu_285_p4 = ap_phi_reg_pp0_iter3_ptrsep_V_flag_0_reg_268.read();
    } else {
        ap_phi_mux_ptrsep_V_flag_1_phi_fu_285_p4 = ap_phi_reg_pp0_iter3_ptrsep_V_flag_1_reg_281.read();
    }
}

void stream::thread_ap_phi_mux_ptrsep_V_flag_2_phi_fu_306_p4() {
    if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read())) {
        ap_phi_mux_ptrsep_V_flag_2_phi_fu_306_p4 = ap_phi_mux_ptrsep_V_flag_1_phi_fu_285_p4.read();
    } else if (esl_seteq<1,1,1>(icmp_ln895_reg_855.read(), ap_const_lv1_1)) {
        ap_phi_mux_ptrsep_V_flag_2_phi_fu_306_p4 = ap_phi_reg_pp0_iter3_ptrsep_V_flag_0_reg_268.read();
    } else {
        ap_phi_mux_ptrsep_V_flag_2_phi_fu_306_p4 = ap_phi_reg_pp0_iter3_ptrsep_V_flag_2_reg_303.read();
    }
}

void stream::thread_ap_phi_mux_ptrsep_V_new_1_phi_fu_296_p4() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln879_1_reg_885.read()))) {
        ap_phi_mux_ptrsep_V_new_1_phi_fu_296_p4 = t_V_3_reg_258.read();
    } else {
        ap_phi_mux_ptrsep_V_new_1_phi_fu_296_p4 = ap_phi_reg_pp0_iter3_ptrsep_V_new_1_reg_293.read();
    }
}

void stream::thread_ap_phi_mux_ptrsep_V_new_2_phi_fu_317_p4() {
    if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read())) {
        ap_phi_mux_ptrsep_V_new_2_phi_fu_317_p4 = ap_phi_mux_ptrsep_V_new_1_phi_fu_296_p4.read();
    } else if (esl_seteq<1,1,1>(icmp_ln895_reg_855.read(), ap_const_lv1_1)) {
        ap_phi_mux_ptrsep_V_new_2_phi_fu_317_p4 = ap_const_lv9_0;
    } else {
        ap_phi_mux_ptrsep_V_new_2_phi_fu_317_p4 = ap_phi_reg_pp0_iter3_ptrsep_V_new_2_reg_314.read();
    }
}

void stream::thread_ap_phi_mux_t_V_3_phi_fu_261_p4() {
    if (esl_seteq<1,1,1>(ap_const_lv1_0, or_ln27_reg_847.read())) {
        ap_phi_mux_t_V_3_phi_fu_261_p4 = ap_sig_allocacmp_t_V_1.read();
    } else if (esl_seteq<1,1,1>(or_ln27_reg_847.read(), ap_const_lv1_1)) {
        ap_phi_mux_t_V_3_phi_fu_261_p4 = add_ln700_1_fu_655_p2.read();
    } else {
        ap_phi_mux_t_V_3_phi_fu_261_p4 = ap_phi_reg_pp0_iter2_t_V_3_reg_258.read();
    }
}

void stream::thread_ap_phi_reg_pp0_iter0_ptrsep_V_flag_0_reg_268() {
    ap_phi_reg_pp0_iter0_ptrsep_V_flag_0_reg_268 =  (sc_lv<1>) ("X");
}

void stream::thread_ap_phi_reg_pp0_iter0_ptrsep_V_flag_1_reg_281() {
    ap_phi_reg_pp0_iter0_ptrsep_V_flag_1_reg_281 =  (sc_lv<1>) ("X");
}

void stream::thread_ap_phi_reg_pp0_iter0_ptrsep_V_new_1_reg_293() {
    ap_phi_reg_pp0_iter0_ptrsep_V_new_1_reg_293 =  (sc_lv<9>) ("XXXXXXXXX");
}

void stream::thread_ap_phi_reg_pp0_iter2_t_V_3_reg_258() {
    ap_phi_reg_pp0_iter2_t_V_3_reg_258 =  (sc_lv<9>) ("XXXXXXXXX");
}

void stream::thread_ap_phi_reg_pp0_iter3_p_0202_reg_325() {
    ap_phi_reg_pp0_iter3_p_0202_reg_325 =  (sc_lv<1>) ("X");
}

void stream::thread_ap_phi_reg_pp0_iter3_ptrsep_V_flag_2_reg_303() {
    ap_phi_reg_pp0_iter3_ptrsep_V_flag_2_reg_303 =  (sc_lv<1>) ("X");
}

void stream::thread_ap_phi_reg_pp0_iter3_ptrsep_V_new_2_reg_314() {
    ap_phi_reg_pp0_iter3_ptrsep_V_new_2_reg_314 =  (sc_lv<9>) ("XXXXXXXXX");
}

void stream::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void stream::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to2.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void stream::thread_ap_return() {
    ap_return = ap_phi_mux_p_0202_phi_fu_328_p4.read();
}

void stream::thread_ap_sig_allocacmp_readidx_V_load() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_sig_allocacmp_readidx_V_load = add_ln214_fu_755_p2.read();
    } else {
        ap_sig_allocacmp_readidx_V_load = readidx_V.read();
    }
}

void stream::thread_ap_sig_allocacmp_t_V_1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_ptrsep_V_flag_2_phi_fu_306_p4.read()))) {
        ap_sig_allocacmp_t_V_1 = ap_phi_mux_ptrsep_V_new_2_phi_fu_317_p4.read();
    } else {
        ap_sig_allocacmp_t_V_1 = ptrsep_V.read();
    }
}

void stream::thread_brams_V_0_address0() {
    brams_V_0_address0 =  (sc_lv<9>) (zext_ln544_fu_615_p1.read());
}

void stream::thread_brams_V_0_address1() {
    brams_V_0_address1 =  (sc_lv<9>) (zext_ln544_1_fu_672_p1.read());
}

void stream::thread_brams_V_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        brams_V_0_ce0 = ap_const_logic_1;
    } else {
        brams_V_0_ce0 = ap_const_logic_0;
    }
}

void stream::thread_brams_V_0_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        brams_V_0_ce1 = ap_const_logic_1;
    } else {
        brams_V_0_ce1 = ap_const_logic_0;
    }
}

void stream::thread_brams_V_0_d0() {
    brams_V_0_d0 = (!lastvalid_read_reg_772.read()[0].is_01())? sc_lv<67>(): ((lastvalid_read_reg_772.read()[0].to_bool())? sel_tmp1_fu_593_p5.read(): p_Result_3_3_fu_476_p5.read());
}

void stream::thread_brams_V_0_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(or_ln27_fu_381_p2.read(), ap_const_lv1_1))) {
        brams_V_0_we0 = ap_const_logic_1;
    } else {
        brams_V_0_we0 = ap_const_logic_0;
    }
}

void stream::thread_brams_V_1_address0() {
    brams_V_1_address0 =  (sc_lv<9>) (zext_ln544_fu_615_p1.read());
}

void stream::thread_brams_V_1_address1() {
    brams_V_1_address1 =  (sc_lv<9>) (zext_ln544_1_fu_672_p1.read());
}

void stream::thread_brams_V_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        brams_V_1_ce0 = ap_const_logic_1;
    } else {
        brams_V_1_ce0 = ap_const_logic_0;
    }
}

void stream::thread_brams_V_1_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        brams_V_1_ce1 = ap_const_logic_1;
    } else {
        brams_V_1_ce1 = ap_const_logic_0;
    }
}

void stream::thread_brams_V_1_d0() {
    brams_V_1_d0 = (!lastvalid_read_reg_772.read()[0].is_01())? sc_lv<67>(): ((lastvalid_read_reg_772.read()[0].to_bool())? tmp_6_fu_575_p4.read(): tmp_fu_413_p4.read());
}

void stream::thread_brams_V_1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(or_ln27_fu_381_p2.read(), ap_const_lv1_1))) {
        brams_V_1_we0 = ap_const_logic_1;
    } else {
        brams_V_1_we0 = ap_const_logic_0;
    }
}

void stream::thread_brams_V_2_address0() {
    brams_V_2_address0 =  (sc_lv<9>) (zext_ln544_fu_615_p1.read());
}

void stream::thread_brams_V_2_address1() {
    brams_V_2_address1 =  (sc_lv<9>) (zext_ln544_1_fu_672_p1.read());
}

void stream::thread_brams_V_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        brams_V_2_ce0 = ap_const_logic_1;
    } else {
        brams_V_2_ce0 = ap_const_logic_0;
    }
}

void stream::thread_brams_V_2_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        brams_V_2_ce1 = ap_const_logic_1;
    } else {
        brams_V_2_ce1 = ap_const_logic_0;
    }
}

void stream::thread_brams_V_2_d0() {
    brams_V_2_d0 = (!lastvalid_read_reg_772.read()[0].is_01())? sc_lv<67>(): ((lastvalid_read_reg_772.read()[0].to_bool())? tmp_5_fu_502_p4.read(): tmp_2_fu_434_p4.read());
}

void stream::thread_brams_V_2_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(or_ln27_fu_381_p2.read(), ap_const_lv1_1))) {
        brams_V_2_we0 = ap_const_logic_1;
    } else {
        brams_V_2_we0 = ap_const_logic_0;
    }
}

void stream::thread_brams_V_3_address0() {
    brams_V_3_address0 =  (sc_lv<9>) (zext_ln544_fu_615_p1.read());
}

void stream::thread_brams_V_3_address1() {
    brams_V_3_address1 =  (sc_lv<9>) (zext_ln544_1_fu_672_p1.read());
}

void stream::thread_brams_V_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        brams_V_3_ce0 = ap_const_logic_1;
    } else {
        brams_V_3_ce0 = ap_const_logic_0;
    }
}

void stream::thread_brams_V_3_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        brams_V_3_ce1 = ap_const_logic_1;
    } else {
        brams_V_3_ce1 = ap_const_logic_0;
    }
}

void stream::thread_brams_V_3_d0() {
    brams_V_3_d0 = (!lastvalid_read_reg_772.read()[0].is_01())? sc_lv<67>(): ((lastvalid_read_reg_772.read()[0].to_bool())? tmp_4_fu_488_p4.read(): tmp_3_fu_459_p4.read());
}

void stream::thread_brams_V_3_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(or_ln27_fu_381_p2.read(), ap_const_lv1_1))) {
        brams_V_3_we0 = ap_const_logic_1;
    } else {
        brams_V_3_we0 = ap_const_logic_0;
    }
}

void stream::thread_candout_V() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0))) {
        if (esl_seteq<1,1,1>(icmp_ln895_reg_855.read(), ap_const_lv1_1)) {
            candout_V = ap_const_lv64_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read())) {
            candout_V = p_Val2_s_fu_708_p6.read().range(66, 3);
        } else {
            candout_V = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        candout_V = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void stream::thread_candout_V_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
          esl_seteq<1,1,1>(icmp_ln895_reg_855.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read())))) {
        candout_V_ap_vld = ap_const_logic_1;
    } else {
        candout_V_ap_vld = ap_const_logic_0;
    }
}

void stream::thread_first() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0))) {
        if (esl_seteq<1,1,1>(icmp_ln895_reg_855.read(), ap_const_lv1_1)) {
            first =  (sc_logic) (ap_const_lv1_0[0]);
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read())) {
            first =  (sc_logic) (p_Val2_s_fu_708_p6.read()[1]);
        } else {
            first = sc_logic('X');
        }
    } else {
        first = sc_logic('X');
    }
}

void stream::thread_first_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
          esl_seteq<1,1,1>(icmp_ln895_reg_855.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read())))) {
        first_ap_vld = ap_const_logic_1;
    } else {
        first_ap_vld = ap_const_logic_0;
    }
}

void stream::thread_icmp_ln791_1_fu_371_p2() {
    icmp_ln791_1_fu_371_p2 = (!or_ln791_fu_359_p2.read().is_01() || !ap_const_lv64_0.is_01())? sc_lv<1>(): sc_lv<1>(or_ln791_fu_359_p2.read() != ap_const_lv64_0);
}

void stream::thread_icmp_ln791_fu_365_p2() {
    icmp_ln791_fu_365_p2 = (!or_ln791_fu_359_p2.read().is_01() || !ap_const_lv64_0.is_01())? sc_lv<1>(): sc_lv<1>(or_ln791_fu_359_p2.read() == ap_const_lv64_0);
}

void stream::thread_icmp_ln879_1_fu_684_p2() {
    icmp_ln879_1_fu_684_p2 = (!ap_sig_allocacmp_readidx_V_load.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(ap_sig_allocacmp_readidx_V_load.read() == ap_const_lv2_3);
}

void stream::thread_icmp_ln879_2_fu_341_p2() {
    icmp_ln879_2_fu_341_p2 = (!candin_1_V.read().is_01() || !ap_const_lv64_0.is_01())? sc_lv<1>(): sc_lv<1>(candin_1_V.read() == ap_const_lv64_0);
}

void stream::thread_icmp_ln879_3_fu_353_p2() {
    icmp_ln879_3_fu_353_p2 = (!candin_3_V.read().is_01() || !ap_const_lv64_0.is_01())? sc_lv<1>(): sc_lv<1>(candin_3_V.read() == ap_const_lv64_0);
}

void stream::thread_icmp_ln879_4_fu_347_p2() {
    icmp_ln879_4_fu_347_p2 = (!candin_2_V.read().is_01() || !ap_const_lv64_0.is_01())? sc_lv<1>(): sc_lv<1>(candin_2_V.read() != ap_const_lv64_0);
}

void stream::thread_icmp_ln879_fu_335_p2() {
    icmp_ln879_fu_335_p2 = (!candin_0_V.read().is_01() || !ap_const_lv64_0.is_01())? sc_lv<1>(): sc_lv<1>(candin_0_V.read() != ap_const_lv64_0);
}

void stream::thread_icmp_ln895_fu_662_p2() {
    icmp_ln895_fu_662_p2 = (!ap_phi_mux_t_V_3_phi_fu_261_p4.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_t_V_3_phi_fu_261_p4.read() == ap_const_lv9_0);
}

void stream::thread_last() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0))) {
        if (esl_seteq<1,1,1>(icmp_ln895_reg_855.read(), ap_const_lv1_1)) {
            last =  (sc_logic) (ap_const_lv1_0[0]);
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read())) {
            last =  (sc_logic) (p_Val2_s_fu_708_p6.read()[2]);
        } else {
            last = sc_logic('X');
        }
    } else {
        last = sc_logic('X');
    }
}

void stream::thread_last_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
          esl_seteq<1,1,1>(icmp_ln895_reg_855.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln895_reg_855.read())))) {
        last_ap_vld = ap_const_logic_1;
    } else {
        last_ap_vld = ap_const_logic_0;
    }
}

void stream::thread_or_ln27_fu_381_p2() {
    or_ln27_fu_381_p2 = (write_r.read() | eventstart_read_reg_783.read());
}

void stream::thread_or_ln69_fu_635_p2() {
    or_ln69_fu_635_p2 = (lastvalid_read_reg_772.read() | eventstart_read_reg_783.read());
}

void stream::thread_or_ln791_1_fu_512_p2() {
    or_ln791_1_fu_512_p2 = (icmp_ln879_reg_795.read() | xor_ln879_fu_408_p2.read());
}

void stream::thread_or_ln791_2_fu_517_p2() {
    or_ln791_2_fu_517_p2 = (or_ln791_1_fu_512_p2.read() | icmp_ln791_1_reg_841.read());
}

void stream::thread_or_ln791_fu_359_p2() {
    or_ln791_fu_359_p2 = (candin_3_V.read() | candin_2_V.read());
}

void stream::thread_p_Result_18_1_fu_397_p5() {
    p_Result_18_1_fu_397_p5 = esl_partset<67,67,64,32,32>(ap_const_lv67_0, candin_1_V_read_reg_803.read(), ap_const_lv32_3, ap_const_lv32_42);
}

void stream::thread_p_Result_18_2_fu_423_p5() {
    p_Result_18_2_fu_423_p5 = esl_partset<67,67,64,32,32>(ap_const_lv67_0, candin_2_V_read_reg_814.read(), ap_const_lv32_3, ap_const_lv32_42);
}

void stream::thread_p_Result_18_3_fu_443_p5() {
    p_Result_18_3_fu_443_p5 = esl_partset<67,67,64,32,32>(ap_const_lv67_0, candin_3_V_read_reg_825.read(), ap_const_lv32_3, ap_const_lv32_42);
}

void stream::thread_p_Result_2_fu_721_p1() {
    p_Result_2_fu_721_p1 = p_Val2_s_fu_708_p6.read().range(1-1, 0);
}

void stream::thread_p_Result_3_3_fu_476_p5() {
    p_Result_3_3_fu_476_p5 = esl_partset<67,67,2,32,32>(p_Result_s_fu_386_p5.read(), tmp_1_fu_469_p3.read(), ap_const_lv32_0, ap_const_lv32_1);
}

void stream::thread_p_Result_s_fu_386_p5() {
    p_Result_s_fu_386_p5 = esl_partset<67,67,64,32,32>(ap_const_lv67_0, candin_0_V_read_reg_789.read(), ap_const_lv32_3, ap_const_lv32_42);
}

void stream::thread_sel_tmp1_fu_593_p5() {
    sel_tmp1_fu_593_p5 = esl_concat<66,1>(esl_concat<65,1>(esl_concat<64,1>(candin_0_V_read_reg_789.read(), and_ln791_4_fu_557_p2.read()), ap_const_lv1_0), icmp_ln879_reg_795.read());
}

void stream::thread_tmp_1_fu_469_p3() {
    tmp_1_fu_469_p3 = esl_concat<1,1>(ap_const_lv1_0, icmp_ln879_reg_795.read());
}

void stream::thread_tmp_2_fu_434_p4() {
    tmp_2_fu_434_p4 = esl_bitset<67,67,32,1>(p_Result_18_2_fu_423_p5.read(), ap_const_lv32_0, icmp_ln879_4_reg_819.read());
}

void stream::thread_tmp_3_fu_459_p4() {
    tmp_3_fu_459_p4 = esl_bitset<67,67,32,1>(p_Result_18_3_fu_443_p5.read(), ap_const_lv32_0, xor_ln879_1_fu_454_p2.read());
}

void stream::thread_tmp_4_fu_488_p4() {
    tmp_4_fu_488_p4 = esl_bitset<67,67,32,1>(tmp_3_fu_459_p4.read(), ap_const_lv32_2, xor_ln879_1_fu_454_p2.read());
}

void stream::thread_tmp_5_fu_502_p4() {
    tmp_5_fu_502_p4 = esl_bitset<67,67,32,1>(tmp_2_fu_434_p4.read(), ap_const_lv32_2, and_ln791_fu_498_p2.read());
}

void stream::thread_tmp_6_fu_575_p4() {
    tmp_6_fu_575_p4 = esl_bitset<67,67,32,1>(tmp_fu_413_p4.read(), ap_const_lv32_2, and_ln791_5_fu_569_p2.read());
}

void stream::thread_tmp_fu_413_p4() {
    tmp_fu_413_p4 = esl_bitset<67,67,32,1>(p_Result_18_1_fu_397_p5.read(), ap_const_lv32_0, xor_ln879_fu_408_p2.read());
}

void stream::thread_xor_ln69_fu_639_p2() {
    xor_ln69_fu_639_p2 = (lastvalid_read_reg_772.read() ^ ap_const_lv1_1);
}

void stream::thread_xor_ln791_1_fu_563_p2() {
    xor_ln791_1_fu_563_p2 = (and_ln791_4_fu_557_p2.read() ^ ap_const_lv1_1);
}

void stream::thread_xor_ln791_fu_543_p2() {
    xor_ln791_fu_543_p2 = (icmp_ln791_1_reg_841.read() ^ ap_const_lv1_1);
}

void stream::thread_xor_ln879_1_fu_454_p2() {
    xor_ln879_1_fu_454_p2 = (icmp_ln879_3_reg_830.read() ^ ap_const_lv1_1);
}

void stream::thread_xor_ln879_fu_408_p2() {
    xor_ln879_fu_408_p2 = (icmp_ln879_2_reg_808.read() ^ ap_const_lv1_1);
}

void stream::thread_zext_ln544_1_fu_672_p1() {
    zext_ln544_1_fu_672_p1 = esl_zext<64,9>(rdptr_V.read());
}

void stream::thread_zext_ln544_fu_615_p1() {
    zext_ln544_fu_615_p1 = esl_zext<64,9>(wrptr_V.read());
}

void stream::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm =  (sc_lv<1>) ("X");
            break;
    }
}

void stream::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"candin_0_V\" :  \"" << candin_0_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"candin_1_V\" :  \"" << candin_1_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"candin_2_V\" :  \"" << candin_2_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"candin_3_V\" :  \"" << candin_3_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"candout_V\" :  \"" << candout_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"candout_V_ap_vld\" :  \"" << candout_V_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"eventstart\" :  \"" << eventstart.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"lastvalid\" :  \"" << lastvalid.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"first\" :  \"" << first.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"first_ap_vld\" :  \"" << first_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"last\" :  \"" << last.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"last_ap_vld\" :  \"" << last_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

