// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="writeheader,hls_ip_2019_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flga2104-2L-e,HLS_INPUT_CLOCK=2.778000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=0.411000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=63,HLS_VERSION=2019_2_1}" *)

module writeheader (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bx_V,
        orbit_V,
        run_V,
        write_r,
        ap_return
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] bx_V;
input  [29:0] orbit_V;
input  [9:0] run_V;
input   write_r;
output  [63:0] ap_return;

wire   [0:0] select_ln3_fu_72_p0;
wire   [63:0] p_Result_s_fu_60_p5;

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign ap_return = ((select_ln3_fu_72_p0[0:0] === 1'b1) ? p_Result_s_fu_60_p5 : 64'd0);

assign p_Result_s_fu_60_p5 = {{{{run_V}, {orbit_V}}, {bx_V}}, {12'd0}};

assign select_ln3_fu_72_p0 = write_r;

endmodule //writeheader
