// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _writeheader_HH_
#define _writeheader_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct writeheader : public sc_module {
    // Port declarations 9
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<12> > bx_V;
    sc_in< sc_lv<30> > orbit_V;
    sc_in< sc_lv<10> > run_V;
    sc_in< sc_logic > write_r;
    sc_out< sc_lv<64> > ap_return;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    writeheader(sc_module_name name);
    SC_HAS_PROCESS(writeheader);

    ~writeheader();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<1> > select_ln3_fu_72_p0;
    sc_signal< sc_lv<64> > p_Result_s_fu_60_p5;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_p_Result_s_fu_60_p5();
    void thread_select_ln3_fu_72_p0();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
