// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _adder_HH_
#define _adder_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct adder : public sc_module {
    // Port declarations 7
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<10> > a_V;
    sc_in< sc_lv<10> > b_V;
    sc_out< sc_lv<11> > ap_return;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    adder(sc_module_name name);
    SC_HAS_PROCESS(adder);

    ~adder();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<11> > rhs_V_fu_30_p1;
    sc_signal< sc_lv<11> > lhs_V_fu_26_p1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_lhs_V_fu_26_p1();
    void thread_rhs_V_fu_30_p1();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
